const SOCKET_INIT = 'SOCKET_INIT';
const SOCKET_CLOSE = 'SOCKET_CLOSE';

const PLAYERS_UPDATE = 'PLAYERS_UPDATE';
const PLAYER_REMOVE = 'PLAYER_REMOVE';

export {
    SOCKET_INIT,
    SOCKET_CLOSE,

    PLAYERS_UPDATE,
    PLAYER_REMOVE,
};
