const SOCKET_INIT = 'SOCKET_INIT';
const SOCKET_CLOSE = 'SOCKET_CLOSE';

const PLAYER_INVITE = 'PLAYER_REMOVE';
const PLAYERS_UPDATE = 'PLAYERS_UPDATE';

const INVITATION_RECEIVED = 'INVITATION_RECEIVED';
const INVITATION_ACCEPTED = 'INVITATION_ACCEPTED';
const INVITATION_REJECTED = 'INVITATION_REJECTED';

const PLAYER_INVITE_REJECTED = 'PLAYER_INVITE_REJECTED';
const PLAYER_INVITE_ACCEPTED = 'PLAYER_INVITE_ACCEPTED';

const GAME_INIT = 'GAME_INIT';
const NEXT_MOVE = 'NEXT_MOVE';
const RESET_GAME = 'RESET_GAME';
const GAME_INITIATED = 'GAME_INITIATED';
const RECEIVE_NEXT_MOVE = 'RECEIVE_NEXT_MOVE';

const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const LOGOUT_START = 'LOGOUT_START';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export {
    SOCKET_INIT,
    SOCKET_CLOSE,

    PLAYERS_UPDATE,
    PLAYER_INVITE,

    INVITATION_RECEIVED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,

    PLAYER_INVITE_ACCEPTED,
    PLAYER_INVITE_REJECTED,

    GAME_INIT,
    NEXT_MOVE,
    RESET_GAME,
    GAME_INITIATED,
    RECEIVE_NEXT_MOVE,

    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_START,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE,
};
